Add Pills Component and Styling
rbrtsmith/nebula-components pull request #17
Opened 2017-08-21 15:06 UTC by kwood15

Please can you have a look over this thanks - can't tag until contributor

2017-08-22 07:43 UTC, Ehesp requested changes

2017-08-22 07:43 UTC, Ehesp commented on demo/src/Components/Pills/Panel.jsx
> +  children: T.node,
Are children not required here? Or will it just not render and still look ok?

2017-08-22 07:43 UTC, Ehesp commented on demo/src/Components/Pills/Panels.jsx
> +  return (
If activeIndex is only ever a single integer, could we not do:

```
const child = children[activeIndex] || null;
```

2017-08-22 07:43 UTC, Ehesp commented on demo/src/Components/Pills/Pill.jsx
> +Pill.propTypes = {
What about defaultProps?

2017-08-22 07:43 UTC, Ehesp commented on demo/src/Components/Pills/Pills.jsx
> +      activeIndex: 0,
Is there no way to set the default activeIndex to something other than 0?

2017-08-22 07:43 UTC, Ehesp commented on demo/src/Components/Pills/index.jsx
> +            <Pill key={name} disabled={disabled} status={status}>{name}</Pill>)}
Is there a linting enforcement here? usually if props is greater than 1 it would break to new lines

2017-08-22 11:07 UTC, kwood15 commented on demo/src/Components/Pills/index.jsx
> +            <Pill key={name} disabled={disabled} status={status}>{name}</Pill>)}
Have fixed this across all files - will push separate commits for these

2017-08-22 12:19 UTC, kwood15 commented on demo/src/Components/Pills/Panels.jsx
> +  return (
Done

2017-08-22 12:21 UTC, kwood15 commented on demo/src/Components/Pills/Panel.jsx
> +  children: T.node,
Have added required

2017-08-22 12:21 UTC, kwood15 commented on demo/src/Components/Pills/Pill.jsx
> +Pill.propTypes = {
Have added and removed as we turned this rule off initially

2017-08-22 16:16 UTC, rbrtsmith reviewed
I wouldn't put unrelated changes into this PR i.e. you are making a lot of changes in the demo that are unrelated to the pills.  It's much easier to manage smaller PRs aimed at a specific purpose.

2017-08-22 16:16 UTC, rbrtsmith commented on demo/src/Components/Pills/Pill.jsx
> +  return (
Don't get too hooked up on allowing multiple node types for the demo here, it's just to literally test the styling, these React components here aren't being shipped - It's in Nebula-React where we should care about the React side of things.

2017-08-22 16:16 UTC, rbrtsmith commented on demo/.eslintrc
> +    "react/jsx-max-props-per-line" : ['error', {maximum: 1}]
Not sure I agree with this.  Sometimes we want props on a single line depending on the line length.

2017-08-22 16:20 UTC, rbrtsmith commented on demo/src/Components/Pills/Pills.jsx
> +      activeIndex: 0,
This should be possible, but we only really care about this in Nebula React.  Nebula Components just ships Sass components and Nebula React ships the React components themselves.  The bits of React code are just a dumping ground to test out the components as they are built.  Ideally they can be deleted when build properly in Nebula-React and demoed in http://rbrtsmith.com/nebula/
Hope this makes sense!

2017-08-22 16:50 UTC, kwood15 commented on demo/src/Components/Pills/Pills.jsx
> +      activeIndex: 0,
Yes thanks - I tried this reverting to false and it was breaking so left as is - most of these are fixed now - have left the defaultProp one as have to declare values for each - the only rule I have changed is the one re multiline props so once this gets merged will fixed conflicts on other branch I'm working on.

2017-08-22 16:51 UTC, kwood15 commented on demo/.eslintrc
> +    "react/jsx-max-props-per-line" : ['error', {maximum: 1}]
Yes this is why I've only changed this rule as it was raised, have checked all the other components so don't worry

2017-08-22 16:52 UTC, kwood15 commented on demo/src/Components/Pills/Pill.jsx
> +  return (
Yes I will do in future Rob - noted

2017-08-22 16:54 UTC, kwood15 commented
If all ok now could this get merged please cheers @Ehesp

2017-08-23 09:26 UTC, rbrtsmith commented
Want that max-props-per-line rule removed from linting prior to merging.

2017-08-23 09:35 UTC, rbrtsmith commented
Just noticed are these acting like tabs? If so I should have been more precise in the description that they are just intended to be used for things like tags like the pills on the Bootstrap framework.

2017-08-23 09:54 UTC, kwood15 commented
@rbrtsmith - Have removed the multiline prop rule - do you want to raise another story for any new changes for the pills or shall I reacreate another set not tied to tabs? Awaiting this to get merged but if it's not what you want then will leave. Cheers

2017-08-23 10:18 UTC, rbrtsmith commented
I would suggest removing the tab based stuff in this branch before merging
then we don't end up with possible redundant code lingering around.

Thanks!

On 23 Aug 2017 10:54 am, "Kay Wood" <notifications@github.com> wrote:

> @rbrtsmith <https://github.com/rbrtsmith> - Have removed the multiline
> prop rule - do you want to raise another story for any new changes for the
> pills or shall I reacreate another set not tied to tabs? Awaiting this to
> get merged but if it's not what you want then will leave. Cheers
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rbrtsmith/nebula-components/pull/17#issuecomment-324280764>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEwE8fb3wtXMequCGbqdul6eoa59um2Sks5sa_bMgaJpZM4O9eC0>
> .
>

2017-08-23 16:17 UTC, closed without merging